server:
  port: 4000
minio:
  url: http://117.72.36.217:9000
  accessKey: minioadmin
  secretKey: minioadmin


#storage:
#  service:
#    type: minio
#
#spring:
#  application:
#    name: jc-club-oss-dev
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      config:
#        server-addr: 117.72.36.217:8848
#        prefix: ${spring.application.name}
#        group: DEFAULT_GROUP
#        namespace:
#        file-extension: yaml
#      discovery:
#        enabled: true
#        server-addr: 117.72.36.217:8848
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



